### ISSUE TITLE
FileNotFoundError on creating interlis model

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#13]
Possibly happens when java is not installed?

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden 
Traceback (most recent call last):
  File "C:/Users/rfill/.qgis3/python/plugins\projectgenerator\gui\generate_project.py", line 44, in accepted
    if importer.run() == iliimporter.Importer.SUCCESS:
  File "C:/Users/rfill/.qgis3/python/plugins\projectgenerator\libili2pg\iliimporter.py", line 78, in run
    stderr=subprocess.PIPE
  File "C:\OSGEO4~1\apps\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\OSGEO4~1\apps\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by m-kuhn** [comment]
Improved error reporting in https://github.com/opengisch/projectgenerator/releases/tag/v0.2.3
