### ISSUE TITLE
problem generating project form postgres schema (without ili)

### ISSUE THREAD

**Issue by soester** [opengisch/projectgenerator#209]
phyton error:

`An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'lower' 
Traceback (most recent call last):
  File "/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/gui/generate_project.py", line 266, in accepted
    available_layers = generator.layers()
  File "/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libqgsprojectgen/generator/generator.py", line 158, in layers
    fielddef['data_type'])
  File "/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py", line 40, in map_data_types
    data_type = data_type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.0.3-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/sam/Library/Application Support/QGIS/QGIS3/profiles/default/python `

**Comment by m-kuhn** [comment]
@soester can you download the following pg_connector.py file and replace it in your plugin and check if this fixes the issue?

https://raw.githubusercontent.com/opengisch/projectgenerator/c07c934c428936d592fb57cd1e50b8bc7f476c21/projectgenerator/libqgsprojectgen/dbconnector/pg_connector.py

**Comment by soester** [comment]
Yes! @m-kuhn this works!
