### ISSUE TITLE
ilip2g can't be started correctly (ili2pg3.7)

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/projectgenerator#21]
Here is the error message:

-------------------------------------

```
An error has occurred while executing Python code: 

OSError: [WinError 6] Das Handle ist ungültig 
Traceback (most recent call last):
  File "C:/Users/nend/.qgis3/python/plugins\projectgenerator\gui\generate_project.py", line 74, in accepted
    if importer.run() != iliimporter.Importer.SUCCESS:
  File "C:/Users/nend/.qgis3/python/plugins\projectgenerator\libili2pg\iliimporter.py", line 121, in run
    stderr=subprocess.PIPE
  File "C:\Program Files\OSGEO4~1\apps\Python36\lib\subprocess.py", line 665, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Program Files\OSGEO4~1\apps\Python36\lib\subprocess.py", line 898, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Program Files\OSGEO4~1\apps\Python36\lib\subprocess.py", line 948, in _make_inheritable
    _winapi.DUPLICATE_SAME_ACCESS)
OSError: [WinError 6] Das Handle ist ungültig


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 2.99.0-Master Master, baced7b 

Python Path:
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python
C:/Users/nend/.qgis3/python
C:/Users/nend/.qgis3/python/plugins
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\Program Files\OSGEO4~1\bin\python36.zip
C:\Program Files\OSGEO4~1\apps\Python36\DLLs
C:\Program Files\OSGEO4~1\apps\Python36\lib
C:\Program Files\OSGEO4~1\bin
C:\Program Files\OSGEO4~1\apps\Python36
C:\Program Files\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/nend/.qgis3//python
```

**Comment by m-kuhn** [comment]
Reports for similar issues appearing on certain systems can be found on various places on the internet. Unfortunately much less information on how to deal with this is available.

Some ideas:
 * use `shell=True` (if possible with Popen)
 * don't specify `stderr=PIPE`
 * https://www.digitalenginesoftware.com/blog/archives/47-Passing-pipes-to-subprocesses-in-Python-in-Windows.html
 * https://docs.python.org/2/library/subprocess.html#subprocess.STARTUPINFO

We will need to organize a remote desktop session to look into this.
