### ISSUE TITLE
Python error when choosing "Export Interlis Transfer File (.xtf)"

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#260]
Version 3.3.3 together with 3.5.0 Master and 3.4.1.

When you chose the the command "Export Interlis Transfer File (.xtf)" in the menu, the following error occurs:

An error has occurred while executing Python code: 

```
sqlite3.OperationalError: unable to open database file 
Traceback (most recent call last):
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\qgs_project_generator.py", line 145, in show_export_dialog
    dlg = ExportDialog(self.ili2db_configuration)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 186, in __init__
    self.refreshed_export_models_model()
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 218, in refreshed_export_models_model
    self.export_models_model = ExportModels(tool_name, uri_string, schema)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 65, in __init__
    self._db_connector = gpkg_connector.GPKGConnector(uri, None)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\libqgsprojectgen\dbconnector\gpkg_connector.py", line 33, in __init__
    self.conn = qgis.utils.spatialite_connect(uri)
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 594, in spatialite_connect
    con = sqlite3.dbapi2.connect(*args, **kwargs)
sqlite3.OperationalError: unable to open database file


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.1-Madeira Madeira, 8d91a6eea9 
```

**Comment by pramisters** [comment]
On another machine, when executing the same command ("Export Interlis Transfer File"), we get the following error:

Traceback (most recent call last):
  File "C:/Users/nend/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\qgs_project_generator.py", line 145, in show_export_dialog
    dlg = ExportDialog(self.ili2db_configuration)
  File "C:/Users/nend/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 186, in __init__
    self.refreshed_export_models_model()
  File "C:/Users/nend/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 218, in refreshed_export_models_model
    self.export_models_model = ExportModels(tool_name, uri_string, schema)
  File "C:/Users/nend/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\gui\export.py", line 67, in __init__
    self._db_connector = pg_connector.PGConnector(uri, schema)
  File "C:/Users/nend/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\projectgenerator\libqgsprojectgen\dbconnector\pg_connector.py", line 35, in __init__
    self.conn = psycopg2.connect(uri)
  File "C:\Programme\OSGeo4W64\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.1-Madeira Madeira, 8d91a6eea9

**Comment by romefi** [comment]
![image](https://user-images.githubusercontent.com/26796989/48072949-ef15b780-e1dd-11e8-8687-023a0b121481.png)

**Comment by m-kuhn** [comment]
@pramisters can you attach the gpkg from the first comment and the database connection details (IP etc.) from the second one (postgres).
@romefi is the gpkg you are working here one generated with the latest release of the project generator or an older one?

**Comment by pramisters** [comment]
At this moment (when you click on "Export Interlis Transfer File (.xtf)") you haven't selected a gpkg file yet, you even haven't decided yet if you want to export from PostGIS or GeoPackage. So, I have no clue which gpkg/spatiallite file the projectgen is referring to.
