### ISSUE TITLE
Schema "xxx" does not exist

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#38]
The projectgenerator should only search for Schemas that have been imported

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.ProgrammingError: FEHLER:  Schema „al_1700“ existiert nicht 
Traceback (most recent call last):
  File "C:/Users/KANU/.qgis3/python/plugins\projectgenerator\gui\generate_project.py", line 89, in accepted
    available_layers = generator.layers()
  File "C:/Users/KANU/.qgis3/python/plugins\projectgenerator\libqgsprojectgen\generator\postgres\postgrescreator.py", line 62, in layersa
    """)
  File "C:\Program Files\OSGEO4~1\apps\Python36\lib\site-packages\psycopg2\extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: FEHLER:  Schema „al_1700“ existiert nicht



Python-Version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS-Version: 2.99.0-Master Master, baced7b 

Python-Pfad:
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python
C:/Users/KANU/.qgis3/python
C:/Users/KANU/.qgis3/python/plugins
C:/Program Files/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\Program Files\OSGEO4~1\bin\python36.zip
C:\Program Files\OSGEO4~1\apps\Python36\DLLs
C:\Program Files\OSGEO4~1\apps\Python36\lib
C:\Program Files\OSGEO4~1\bin
C:\Program Files\OSGEO4~1\apps\Python36
C:\Program Files\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/KANU/.qgis3//python
```

**Comment by m-kuhn** [comment]
I cannot reproduce this.
Is this still an issue?

**Comment by pramisters** [comment]
No, it seems to be fixed.
