### ISSUE TITLE
Unhandled Internet access error 

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#91]
Using the plugin, my Internet connection died while generating a project and got this error message:

```
projectgenerator.utils.qt_utils.NetworkError: (5, 'Operation canceled') 
Traceback (most recent call last):
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/gui/generate_project.py", line 158, in accepted
    if importer.run() != iliimporter.Importer.SUCCESS:
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libili2pg/iliimporter.py", line 73, in run
    download_file(ILI2PG_URL, tmpfile.name, on_progress=lambda received, total: self.stdout.emit('.'))
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/utils/qt_utils.py", line 122, in download_file
    raise NetworkError(reply.error(), reply.errorString())
projectgenerator.utils.qt_utils.NetworkError: (5, 'Operation canceled')

```

**Comment by m-kuhn** [comment]
Get a stable internet connection ;)

No, seriously... I guess in this case there should be an error message printed in the output log?
